### ISSUE TITLE
Sampo Endpoint Creation!

### ISSUE THREAD

**Issue by WarpWing** [jacobsalmela/sampo#14]
Heyo! Quick question. How do you create your own endpoint in Sampo. I looked in the article and in the shell script and perhaps I'm missing something but I can't find how to create an endpoint. If you could help out would be great. :D

**Comment by betabrandao** [comment]
> Heyo! Quick question. How do you create your own endpoint in Sampo. I looked in the article and in the shell script and perhaps I'm missing something but I can't find how to create an endpoint. If you could help out would be great. :D

I believe that here he provider some information :https://github.com/jacobsalmela/sampo/blob/master/sampo/endpoints.yml
